#------------------------------------------------------------------------------
# GasGen.R - script and TDG functions original written by Nick Beer at
# Columbia Basin Research.  I altered the script to include the lookup data
# within the function, so we didn't need to call a .csv file.
#
# Author and Source: Nick Beer
# (Modified by Ryan Kinzer) - HAS NOT BEEN DONE YET; SCRIPT IS EXACTLY HOW
# NICK ORIGINALLY SENT THE FILE!!!
#------------------------------------------------------------------------------
# Lookup tables
{
  dams <-      c("BON" ,"TDA" ,"JDA" ,"MCN" ,"PRD" ,"WAN" ,"RIS" ,"RRH" ,"WEL" ,"IHR" ,"LMN" ,"LGS" ,"LWG","CHJ", "DWR")
  TDGsideDown <-c("R"   ,"L"   ,"R"   ,"R"   ,"C"   ,"C"   ,"L"   ,"C"   ,"L"   ,"R"   ,"L"   ,"R"   ,"R"  , "R",  "C")
  spillside  <- c("R"   ,"R"   ,"R"   ,"R"   ,"R"   ,"R"   ,"R"   ,"L"   ,"L"   ,"R"   ,"L"   ,"R"   ,"R"  , "R",  "L")
  TDGsideUp  <- c("L"   ,"L"   ,"R"   ,"R"   ,"C"   ,"C"   ,"R"   ,"R"   ,"C"   ,"R"   ,"C"   ,"R"   ,"C"  , "L",  "C")
  Phouseside <- c("L"   ,"L"   ,"L"   ,"L"   ,"L"   ,"L"   ,"L"   ,"R"   ,"R"   ,"L"   ,"R"   ,"L"   ,"L"  , "L",  "R")
  TDGmonDown <- c("WRNO","TDDO","JHAW","MCPW","PRXW","WANW","RIGW","RRDW","WELW","IDSW","LMNW","LGSW","LGNW","CHQW","DWR")
}

gasP <- read.table("./data/allgasparams.csv",sep=",",as.is=TRUE,header=TRUE)
# EQN numbers cross reference other uses.

zTDGMON <- function(site="LWG",FBgas=10,spill=.15,flow=100){
  # based on gas params and other inputs what is the gas the TDG monitoring site?
  # FBgas is the Forebay Gas TDG level ABOVE 100%
  if(grepl("BON",site)){ site <- "BON"}
  pp <- gasP[gasP$Dam == site,]
  #  print(pp)
  attach(pp)
  if(EQN == 62){Gspill <- D0 + D1*flow*spill }
  if(EQN == 30){Gspill <- D0 + D1*exp(D2*flow*spill)}
  k <- entrain_factor
  MONgas <- NA
  if(TDGsideDown[match(site,dams,nomatch=0)]==spillside[match(site,dams,nomatch=0)]){ # Same side
    MONgas <- Gspill*(spill*(1+k) + mxfrac*(1-spill) - mxfrac*spill*k) + FBgas*(1-spill*(1+k)-mxfrac*(1-spill)+mxfrac*spill*k)
  } else{
    MONgas <- Gspill*(spill*(1+k) - spill*mxfrac) + FBgas*(1-spill*(1+k) + spill*mxfrac)
  }
  detach(pp)
  return(MONgas)
}


zTDGSpill <- function(site="LWG",spill=.15,flow=100){
  # based on gas params and other inputs what is the gas generated by spill?
  if(grepl("BON",site)){ site <- "BON"}
  pp <- gasP[gasP$Dam == site,]
  attach(pp)
  if(EQN == 62){Gspill <- D0 + D1*flow*spill }
  if(EQN == 30){Gspill <- D0 + D1*exp(D2*flow*spill)}
  detach(pp)
  return(Gspill)
}


# CAUTION: It is possible to ask for a flow that exceeds the powerhouse's hydraulic capacity. 
# These formulas will compute a gas level, but it will be impossible to attain in the field.
# Extra flow above the hydraulic capacity SHOULD be converted into spill.
# This is not trapped in these computations. For example, IHR powerhouse capacity is 106 KCFS.
# A flow of 200 with spill fraction of 0.15 will never happen there.

# TEST
# Compute the expected TDG at the monitoring site
print(zTDGMON("LWG",FBgas=10, spill=0.9, flow=100))

# Compute the expected TDG in the spill water.
print(zTDGSpill("MCN",spill=0.45, flow=100))

